# Generated by Django 2.2.4 on 2019-08-22 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Material',
            new_name='MaterialPage',
        ),
        migrations.CreateModel(
            name='MaterialItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('link', models.CharField(max_length=250)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Word')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MaterialPage')),
            ],
        ),
    ]
