# Generated by Django 2.2.4 on 2019-08-22 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190822_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialitem',
            name='word',
        ),
        migrations.AlterField(
            model_name='materialitem',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MaterialPage'),
        ),
    ]
