# Generated by Django 2.2.4 on 2019-08-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_materialitem_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialitem',
            name='link',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='materialitem',
            name='title',
            field=models.TextField(max_length=250),
        ),
    ]
