# Generated by Django 2.2.4 on 2019-08-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190822_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpage',
            name='search_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
