# Generated by Django 2.2.4 on 2019-08-22 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_materialpage_search_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.TextField(db_index=True)),
            ],
        ),
        migrations.AlterField(
            model_name='materialitem',
            name='link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='materialitem',
            name='title',
            field=models.TextField(),
        ),
    ]
