# Generated by Django 2.2.4 on 2019-08-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190822_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='link',
            field=models.CharField(db_index=True, max_length=250),
        ),
    ]
